server:
  port: 3011
mybatis:
    mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: debug
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/webflux_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        hikari:
              driver-class-name: com.mysql.cj.jdbc.Driver
              maximum-pool-size: 30

